// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorNamer is an autogenerated mock type for the ErrorNamer type
type ErrorNamer struct {
	mock.Mock
}

// ErrorName provides a mock function with given fields:
func (_m *ErrorNamer) ErrorName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
